### ISSUE TITLE
Version pins for Plone 4.2?

### ISSUE THREAD

**Issue by mauritsvanrees** [eea/eea.facetednavigation#51]
Does anyone know version pins that let eea.facetednavigation work with Plone 4.2?
The facet criteria page is giving a javascript error (`TypeError: this.element.prop is not a function` in the jqueryui script), making it really ugly, and you are not able to add a criterion/facet, only edit existing ones.

I have these pins with Plone 4.2.4, giving the above problem:

```
collective.js.jqueryui = 1.9.2.0
eea.faceted.vocabularies = 4.9
eea.facetednavigation = 6.8
eea.jquery = 7.7
```

On Plone 4.3.3 (that itself pins collective.js.jqueryui to 1.10.3, which you cannot use on Plone 4.2) all seems fine.
